# Imagem base
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SeguroApi.csproj", "./"]
RUN dotnet restore "SeguroApi.csproj"

COPY . .
RUN dotnet build "SeguroApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SeguroApi.csproj" -c Release -o /app/publish

# Final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SeguroApi.dll"]